In [12]:
import pandas as pd

In [13]:
df_control = pd.read_csv("../outputs/control/20261004_234217/results.csv")
df_control[['model','n_folds_ok','accuracy_mean','accuracy_std','auc_mean','auc_std']].iloc[[0,3,4,5]]

,model,n_folds_ok,accuracy_mean,accuracy_std,auc_mean,auc_std
0,FuzzyEspecialistEnsembleClassifier,5,0.898000,0.006182,0.955979,0.006628
3,GMMEspecialistEnsembleClassifier,5,0.862667,0.020155,0.949765,0.004263
4,FuzzyKMedoidsEspecialistEnsembleClassifier,5,0.903333,0.006992,0.954668,0.005570
5,PossibilisticCMeansEspecialistEnsembleClassifier,5,0.894667,0.009092,0.949823,0.006967

In [14]:
df_heavy_tail = pd.read_csv("../outputs/2_1_heavy_tail/20261004_234613/results.csv")
df_heavy_tail[['model','n_folds_ok','accuracy_mean','accuracy_std','auc_mean','auc_std']].iloc[[0,3,4,5]]

,model,n_folds_ok,accuracy_mean,accuracy_std,auc_mean,auc_std
0,FuzzyEspecialistEnsembleClassifier,5,0.904000,0.011813,0.956317,0.006418
3,GMMEspecialistEnsembleClassifier,5,0.896667,0.008944,0.951819,0.010424
4,FuzzyKMedoidsEspecialistEnsembleClassifier,5,0.901333,0.010022,0.954428,0.005403
5,PossibilisticCMeansEspecialistEnsembleClassifier,5,0.903333,0.006325,0.953090,0.006477

In [15]:
df_heavy_tail = pd.read_csv("../outputs/2_2_noise_outliers/20261004_234724/results.csv")
df_heavy_tail[['model','n_folds_ok','accuracy_mean','accuracy_std','auc_mean','auc_std']].iloc[[0,3,4,5]]

,model,n_folds_ok,accuracy_mean,accuracy_std,auc_mean,auc_std
0,FuzzyEspecialistEnsembleClassifier,5,0.888000,0.016546,0.950290,0.009998
3,GMMEspecialistEnsembleClassifier,5,0.882000,0.004522,0.940476,0.005833
4,FuzzyKMedoidsEspecialistEnsembleClassifier,5,0.892667,0.009752,0.951917,0.008954
5,PossibilisticCMeansEspecialistEnsembleClassifier,5,0.880000,0.007601,0.943889,0.011439

In [22]:
experiments_list = [
    'control/20261004_234217',
    '1_1_extreme_scale/20261004_234329',
    '1_2_feature_imbalance/20261004_234454',
    '2_1_heavy_tail/20261004_234613',
    '2_2_noise_outliers/20261004_234724',
    '3_1_data_scarcity/20261004_234755',
    '3_2_data_abundance/20261004_235300',
    '4_1_single_cluster/20261004_235415',
    '4_2_fragmentation/20261004_235533',
]


for experiment in experiments_list:
    df_heavy_tail = pd.read_csv(f"../outputs/{experiment}/results.csv")
    print(experiment)
    print(df_heavy_tail[['model','accuracy_mean','accuracy_std','auc_mean','auc_std']].iloc[[0,3,4,5]])
    print('\n')

control/20261004_234217
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.898000
3                  GMMEspecialistEnsembleClassifier       0.862667
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.903333
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.894667

   accuracy_std  auc_mean   auc_std
0      0.006182  0.955979  0.006628
3      0.020155  0.949765  0.004263
4      0.006992  0.954668  0.005570
5      0.009092  0.949823  0.006967


1_1_extreme_scale/20261004_234329
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.898000
3                  GMMEspecialistEnsembleClassifier       0.863333
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.903333
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.896667

   accuracy_std  auc_mean   auc_std
0      0.006182  0.955837  0.006495
3      0.020221  0.949472  0.004498
4      0.006992  0.954672  0.005569
5      0.009428  0.949694  0.007685


1_2_feature_imbalance/20261004_234454
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.886667
3                  GMMEspecialistEnsembleClassifier       0.746667
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.893333
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.886667

   accuracy_std  auc_mean   auc_std
0      0.013333  0.947147  0.008607
3      0.129099  0.809714  0.117816
4      0.011738  0.950094  0.008874
5      0.014757  0.947432  0.007769


2_1_heavy_tail/20261004_234613
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.904000
3                  GMMEspecialistEnsembleClassifier       0.896667
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.901333
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.903333

   accuracy_std  auc_mean   auc_std
0      0.011813  0.956317  0.006418
3      0.008944  0.951819  0.010424
4      0.010022  0.954428  0.005403
5      0.006325  0.953090  0.006477


2_2_noise_outliers/20261004_234724
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.888000
3                  GMMEspecialistEnsembleClassifier       0.882000
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.892667
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.880000

   accuracy_std  auc_mean   auc_std
0      0.016546  0.950290  0.009998
3      0.004522  0.940476  0.005833
4      0.009752  0.951917  0.008954
5      0.007601  0.943889  0.011439


3_1_data_scarcity/20261004_234755
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier           0.83
3                  GMMEspecialistEnsembleClassifier           0.81
4        FuzzyKMedoidsEspecialistEnsembleClassifier           0.84
5  PossibilisticCMeansEspecialistEnsembleClassifier           0.85

   accuracy_std  auc_mean   auc_std
0      0.050990  0.895576  0.054357
3      0.048990  0.871657  0.035851
4      0.066332  0.879636  0.048210
5      0.031623  0.881515  0.063050


3_2_data_abundance/20261004_235300
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier         0.8988
3                  GMMEspecialistEnsembleClassifier         0.9046
4        FuzzyKMedoidsEspecialistEnsembleClassifier         0.9004
5  PossibilisticCMeansEspecialistEnsembleClassifier         0.8970

   accuracy_std  auc_mean   auc_std
0      0.008588  0.958220  0.004070
3      0.006119  0.959311  0.005023
4      0.006437  0.957925  0.004586
5      0.009550  0.957004  0.003936


4_1_single_cluster/20261004_235415
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.941333
3                  GMMEspecialistEnsembleClassifier       0.792000
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.942000
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.940000

   accuracy_std  auc_mean   auc_std
0      0.015434  0.980764  0.006383
3      0.023247  0.884088  0.016442
4      0.011662  0.982849  0.004288
5      0.010111  0.979231  0.004775


4_2_fragmentation/20261004_235533
                                              model  accuracy_mean  \
0                FuzzyEspecialistEnsembleClassifier       0.738667
3                  GMMEspecialistEnsembleClassifier       0.719333
4        FuzzyKMedoidsEspecialistEnsembleClassifier       0.733333
5  PossibilisticCMeansEspecialistEnsembleClassifier       0.731333

   accuracy_std  auc_mean   auc_std
0      0.009568  0.807996  0.019990
3      0.012184  0.785982  0.021131
4      0.009661  0.807867  0.019721
5      0.024092  0.801960  0.021345